services:
  backend:
    build: .
    expose:
      - "${APPLICATION_PORT}"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - flecto_network
    depends_on:
      - database

  database:
    image: postgres:16.4-alpine
    restart: unless-stopped
    expose:
      - "${PGPORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PGPORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flecto_network

volumes:
  postgres_data:

networks:
  flecto_network:
    external: true